# Generated by Django 2.2.28 on 2022-06-03 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(choices=[('DA', 'dark'), ('L', 'light'), ('D', 'danger'), ('W', 'warning'), ('SE', 'secondary'), ('P', 'primary'), ('S', 'success')], max_length=2)),
            ],
        ),
    ]
