# Generated by Django 2.2.28 on 2022-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
